### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by blanu** [wernerd/Skein3Fish#6]
I would like to use this library, but as there is no LICENSE file I am unclear on the licensing terms.

**Comment by soenkescharnhorst** [comment]
sorry, please use the original of Skein3Fish, there is no license as by schneiders Homepage

**Comment by wernerd** [comment]
This repository contains a set of Skein and Threefish implementations and I used some input from different other sources, see README, credits. The extensions I made use the same licenses as the original sources, except for Go, which is a new implementation and uses GPL3.

Please have a look into the source files, most of them have license/copyright notes (except for a few generated sources).
